### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by ncorbin**
PR includes

- UX Problem
- UX Solution
- 8 Mocks for a review form workflow

### CODE REVIEW

**Comment by mikeauclair** [comment]
Hey there! Please follow the instructions in the README to upload your assignment.

**Comment by ncorbin** [comment]
@mikeauclair Hello! It would not let me add anything directly to the changes.md file directly on your repo as I don't have permissions to do so. I was able to fork the folder and do it this way.
If I'm added to your repo I can submit right to this folder

**Comment by mikeauclair** [comment]
We have a separate process for uploading completed homework - please check https://github.com/adhocteam/homework/blob/master/README.md for instructions

**Comment by ncorbin** [comment]
@mikeauclair Thank you for your help!! I was reading the README in the UX folder instead

**Pull request closed without merging**
